%import common.WS
%import common.WS_INLINE
%import common.INT
// %import common.NEWLINE   

start: anything+

anything: content | chat | generated | opening_command | closing_command | opening_chat | opening_generated | opening_context

content: TEXT | INLINE | MULTILINE | WS

TEXT: /(?:(?!<!--\s*[#\/].*?-->|`.*`|```[^`]+```).)+/
INLINE.99: /`.*?`/
MULTILINE.999: /```.+?```/s

LEFT_COMMENT: /<!--\s*/
RIGHT_COMMENT: /\s*-->\n?/


OPENING_COMMAND_SYMBOL: "#"
CLOSING_COMMAND_SYMBOL: "/"

SEED_COMMAND: "seed"
MODEL_COMMAND: "model"
SYSTEM_COMMAND: "system"
CONVERSATION_COMMAND: "conversation"
CONTEXT_COMMAND: "context"
CHAT_COMMAND: "chat"
GENERATED_COMMAND: "generated"

COMMAND_TEXT: /(?:(?!\s*-->).)+/

opening_seed: LEFT_COMMENT OPENING_COMMAND_SYMBOL SEED_COMMAND WS_INLINE+ INT RIGHT_COMMENT

// Match model 
opening_command: LEFT_COMMENT OPENING_COMMAND_SYMBOL (SEED_COMMAND | MODEL_COMMAND | SYSTEM_COMMAND | CONVERSATION_COMMAND) WS_INLINE+ COMMAND_TEXT RIGHT_COMMENT
closing_command: LEFT_COMMENT CLOSING_COMMAND_SYMBOL (SEED_COMMAND | MODEL_COMMAND | SYSTEM_COMMAND | CONVERSATION_COMMAND) RIGHT_COMMENT

opening_context: LEFT_COMMENT OPENING_COMMAND_SYMBOL CONTEXT_COMMAND WS_INLINE+ COMMAND_TEXT RIGHT_COMMENT

// Match chat with internal part
opening_chat: LEFT_COMMENT OPENING_COMMAND_SYMBOL CHAT_COMMAND WS_INLINE+ COMMAND_TEXT RIGHT_COMMENT
closing_chat: LEFT_COMMENT CLOSING_COMMAND_SYMBOL CHAT_COMMAND WS_INLINE+ COMMAND_TEXT RIGHT_COMMENT
chat.1: opening_chat content+ closing_chat

// Match generated footer text
opening_generated: LEFT_COMMENT OPENING_COMMAND_SYMBOL GENERATED_COMMAND WS_INLINE+ COMMAND_TEXT RIGHT_COMMENT
closing_generated: LEFT_COMMENT CLOSING_COMMAND_SYMBOL GENERATED_COMMAND RIGHT_COMMENT
generated.1: opening_generated content+ closing_generated